on: [push]

name: swagger-validation
jobs:
  test_swagger_editor_validator_remote:
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Remote


    steps:
      - uses: actions/checkout@v3
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.3.2
        with:
          definition-file: config/schemas/openapi.json
